"""Profile models - aggregated callsign profiles generated by AI."""

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Float, ForeignKey, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from tsn_common.models.base import Base, GUID

if TYPE_CHECKING:
    from tsn_common.models.callsign import Callsign


class CallsignProfile(Base):
    """
    Aggregated profile for a callsign, generated by vLLM analysis.
    Summarizes activity, interests, and expertise.
    """

    __tablename__ = "callsign_profiles"

    # One-to-one with Callsign
    callsign_id: Mapped[uuid.UUID] = mapped_column(
        GUID(),
        ForeignKey("callsigns.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
        index=True,
    )

    # AI-generated summary
    profile_summary: Mapped[str | None] = mapped_column(Text, nullable=True)

    # Top interests/topics (array of strings)
    primary_topics: Mapped[list[str] | None] = mapped_column(
        JSON, nullable=True
    )

    # Computed metrics
    activity_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    engagement_score: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Relationship
    callsign: Mapped["Callsign"] = relationship(back_populates="profile")

    def __repr__(self) -> str:
        return f"<CallsignProfile(callsign_id={self.callsign_id})>"

    def to_dict(self) -> dict:
        return {
            **super().to_dict(),
            "callsign_id": str(self.callsign_id),
            "profile_summary": self.profile_summary,
            "primary_topics": self.primary_topics,
            "activity_score": self.activity_score,
            "engagement_score": self.engagement_score,
        }
